"""Application constants."""

APP_VERSION = "1.0.0"

SAMPLE_RATE = 16000  # Whisper expects 16 kHz
IDLE_ICON = "🎤"
RECORDING_ICON = "🎙️"
PROCESSING_ICON = "⚙️"
DOWNLOADING_ICON = "⬇️"
HOTKEY = "<cmd>+<alt>+<f8>"
HOTKEY_LABEL = "Cmd+Option+F8"
RECORDING_START_TIMEOUT_SEC = 10
RECORDING_STALL_TIMEOUT_SEC = 25
